import Head from "next/head";
import ServiceDetail from "../src/Components/Pages/ServicesPage/ServiceDetail";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import NewDetail from "../src/Components/Pages/News/Detail";

export default function Home() {
    const router =useRouter()
    const id=router.query.id

    
    console.log(id);
    return (
        <div>
            <Head>
                <title>Anorhome</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NewDetail id={id}/>
        </div>
    )
}