import Head from "next/head";
import ProjectsPage from "../src/Components/Pages/ProjectsPage";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProjectsPage />
        </div>
    )
}